apiVersion: v2
name: csiapp
description: A sample of CSI in AKS with different identity methods
type: application
version: 0.1.0 #chart version
appVersion: "1.0.1" #your app version (used as an image tag)
