{{- if .Values.useCSIdriver -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "azure-{{ include "app.name" . }}-{{ .Values.keyvaultName }}"
spec:
  provider: azure
  secretObjects:
  - secretName: arbitarySecret
    type: Opaque
    data:
    - objectName: "arbitarySecret"
      key: arbitarySecret
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.azureKVIdentity.clientId }}"
    keyvaultName: {{ .Values.keyvaultName }} # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: arbitarySecret
          objectType: secret
    tenantId: {{ .Values.azureKVIdentity.tenantId }} # the tenant ID of the KeyVault
{{- end }}
