{{- if eq .Values.azureKVIdentity.type "workload" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  annotations:
    azure.workload.identity/client-id:  {{ .Values.azureWorkloadIdentity.clientId }}
    azure.workload.identity/tenant-id:  {{ .Values.azureWorkloadIdentity.tenantId }}
  labels:
    azure.workload.identity/use: "true"
{{- end }}
