replicaCount: 1

nameOverride: ""

image:
  repository: ghcr.io/azure/azure-workload-identity/msal-go
  pullPolicy: IfNotPresent #Always
  tag: "latest" #image tag should be set in Chart.yaml - but where it's a strange tag, just override here

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: "" #Leave empty and it'll default to the name of the app, thanks to the _helpers.tpl

azureWorkloadIdentity:
  clientId: ""
  tenantId: ""

keyvaultName: ""
secretName: ""

podSecurityContext: {}
  # fsGroup: 2000