{{- if .Values.useCSIdriver -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "azure-{{ include "app.name" . }}-{{ .Values.keyvaultName }}"
spec:
  provider: azure
  secretObjects:
  - secretName: arbitrarySecret
    type: Opaque
    data:
    - objectName: "arbitrarySecret"
      key: arbitrarySecret
  parameters:
    clientID: {{ .Values.azureWorkloadIdentity.clientId }} # client id of the Azure AD app/identity to use for workload identity
    keyvaultName: {{ .Values.keyvaultName }} # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: arbitrarySecret
          objectType: secret
    tenantId: {{ .Values.azureWorkloadIdentity.tenantId }} # the tenant ID of the KeyVault
{{- end }}
